# -*- coding: utf-8 -*-
"""Quantize FP32 ONNX models to true FP16 (weights + activations) using Olive.

True FP16 = both weights AND activations are FP16, with FP16 inputs/outputs.

This is different from W16A32 (which keeps activations FP32):
  - W16A32: FP16 weights + Cast(FP16->FP32) + FP32 activations (DML-stable)
  - True FP16: FP16 weights + FP16 activations (smaller, faster on DML, but
    may have precision issues in sensitive layers)

Uses Olive's OnnxQuantization pass with QuantType.FLOAT16 for both weights and
activations. Calibration data (generated by generate_fp16_calibration.py) is
used to determine activation ranges and identify sensitive tensors that should
stay FP32.

The existing fp16_backup folder contains true FP16 models (mixed opsets 17/18/20).
This script produces new true FP16 models with:
  - Consistent opset 20 (matching FP32 production models)
  - Calibration-aware activation handling
  - Olive DML optimization passes applied

IMPORTANT — VOCODER TRUE FP16 IS NOT VIABLE:
  The vocoder_dml model has THREE structural issues that make TrueFP16 produce
  silent output (cos=0.0004, std=0.74 vs FP32 baseline):
    1. ISTFT initializers with tiny values (~1e-12) get truncated to 1e-7
       (FP16 minimum normal), destroying ISTFT reconstruction.
    2. Shape calculation values (num_frames × hop_size = 240000) overflow FP16
       max (65504) when converted to FP16 constants.
    3. CRITICAL: 20 ConvNeXt backbone weight matrices (onnx::MatMul_1020
       through onnx::MatMul_1076) have tiny values as small as 4.83e-10.
       FP16 truncates these to 0, destroying the network behavior.

  Blocking ISTFT nodes (node_block_list) and shape overflow nodes does NOT fix
  the issue because the ConvNeXt backbone itself is broken in FP16.

  Solution: Use W16A32 for vocoder (cos=0.999997, snr=51.76 dB).
  The fp16/ production directory for vocoder should be populated by running
  convert_fp16_w16a32.py, NOT this script. This script skips vocoder_dml by
  default (see VOCODER_SKIP=True below).

Usage: python quantize_fp16_true.py [--calib-dir PATH] [--output-dir PATH]
"""
import os
import sys
import shutil
import logging
import json
import numpy as np
import onnx
from pathlib import Path
from onnx import helper, numpy_helper, TensorProto, shape_inference

# Suppress ONNX Runtime warnings
os.environ['ORT_LOGGING_LEVEL'] = '3'
os.environ['ONNXRUNTIME_LOGGING_LEVEL'] = '3'

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = SCRIPT_DIR
FP32_DIR = os.path.join(PROJECT_DIR, 'onnx_models')  # FP32 production models
CALIB_DIR = os.path.join(PROJECT_DIR, 'calibrate', 'data', 'fp16_calib')
DEFAULT_OUTPUT_DIR = os.path.join(PROJECT_DIR, 'onnx_models', 'fp16_true')

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# Inline resolve_neg1_in_reshape_shapes to avoid importing export_shared
# (which triggers heavy imports of transformers/torch/soulxsinger).
try:
    import sympy
    HAS_SYMPY = True
except ImportError:
    HAS_SYMPY = False


def resolve_neg1_in_reshape_shapes(model):
    """Replace -1 in Reshape shape Concat with computed static value.

    DML EP doesn't support -1 in shape tensor (returns E_INVALIDARG 0x80070057).
    Compute -1 statically using sympy to cancel dynamic dimensions.
    """
    if not HAS_SYMPY:
        logger.info("  resolve_neg1: sympy not available, skipping")
        return model

    graph = model.graph
    vi_map = {vi.name: vi for vi in graph.value_info}
    for vi in graph.input:
        vi_map[vi.name] = vi
    for vi in graph.output:
        vi_map[vi.name] = vi
    init_map = {init.name: init for init in graph.initializer}

    def get_shape(vi_name):
        if vi_name not in vi_map:
            return None
        t = vi_map[vi_name].type.tensor_type
        if t.elem_type == 0:
            return None
        dims = []
        for d in t.shape.dim:
            if d.dim_value:
                dims.append(d.dim_value)
            elif d.dim_param:
                dims.append(d.dim_param)
            else:
                dims.append(None)
        return dims

    def get_shape_node_dim(shape_node):
        x_name = shape_node.input[0]
        x_shape = get_shape(x_name)
        if x_shape is None:
            return None
        start = 0
        end = len(x_shape)
        for attr in shape_node.attribute:
            if attr.name == 'start':
                start = attr.i
            elif attr.name == 'end':
                end = attr.i
        if end - start != 1:
            return None
        idx = start if start >= 0 else start + len(x_shape)
        if 0 <= idx < len(x_shape):
            return x_shape[idx]
        return None

    shape_nodes = {}
    for node in graph.node:
        if node.op_type == 'Shape':
            shape_nodes[node.output[0]] = node

    symbol_map = {}

    def get_symbol(name):
        if name not in symbol_map:
            symbol_map[name] = sympy.Symbol(name)
        return symbol_map[name]

    resolved = 0
    node_list_snapshot = list(graph.node)
    for node in node_list_snapshot:
        if node.op_type != 'Reshape' or len(node.input) < 2:
            continue
        shape_input = node.input[1]
        data_input = node.input[0]
        concat_node = None
        for n2 in node_list_snapshot:
            if n2.op_type == 'Concat' and shape_input in n2.output:
                concat_node = n2
                break
        if concat_node is None:
            continue
        neg1_init_name = None
        for inp in concat_node.input:
            if inp in init_map:
                arr = numpy_helper.to_array(init_map[inp])
                if arr.size == 1 and arr.item() == -1:
                    neg1_init_name = inp
                    break
        if neg1_init_name is None:
            continue
        data_shape = get_shape(data_input)
        if data_shape is None:
            continue
        total = sympy.Integer(1)
        for dim in data_shape:
            if isinstance(dim, int):
                total *= dim
            elif isinstance(dim, str):
                total *= get_symbol(dim)
            else:
                total = None
                break
        if total is None:
            continue
        known_prod = sympy.Integer(1)
        for inp in concat_node.input:
            if inp == neg1_init_name:
                continue
            if inp in init_map:
                arr = numpy_helper.to_array(init_map[inp])
                if arr.size == 1:
                    known_prod *= int(arr.item())
                else:
                    known_prod = None
                    break
            elif inp in shape_nodes:
                dim = get_shape_node_dim(shape_nodes[inp])
                if dim is None:
                    known_prod = None
                    break
                if isinstance(dim, int):
                    known_prod *= dim
                elif isinstance(dim, str):
                    known_prod *= get_symbol(dim)
                else:
                    known_prod = None
                    break
            else:
                known_prod = None
                break
        if known_prod is None:
            continue
        neg1_val = sympy.simplify(total / known_prod)
        if not neg1_val.is_Integer:
            continue
        neg1_int = int(neg1_val)
        new_init_name = f"{neg1_init_name}_resolved_{neg1_int}"
        new_arr = np.array([neg1_int], dtype=np.int64)
        new_init = numpy_helper.from_array(new_arr, name=new_init_name)
        graph.initializer.append(new_init)
        for i, inp in enumerate(concat_node.input):
            if inp == neg1_init_name:
                concat_node.input[i] = new_init_name
                break
        resolved += 1

    if resolved:
        logger.info(f"  resolve_neg1: resolved {resolved} -1 values in Reshape shapes")
    return model

# Models to quantize (same 9 as W16A32)
# NOTE: vocoder_dml is excluded from TrueFP16 quantization — see module docstring
# for the technical reason (ConvNeXt backbone tiny weight values + ISTFT + shape overflow).
# Use convert_fp16_w16a32.py to generate the production fp16/vocoder_dml.onnx instead.
VOCODER_SKIP = True  # Set to False only for diagnostic purposes (output will be broken)

MODELS = [
    'diff_step_dml',
    'preflow',
    'cond_emb',
    'mel_transform',
    'note_text_encoder',
    'note_pitch_encoder',
    'note_type_encoder',
    'f0_encoder',
]
if not VOCODER_SKIP:
    MODELS.insert(1, 'vocoder_dml')  # keep original ordering when explicitly enabled


# ============================================================
# Calibration data reader for Olive
# ============================================================

class NpzCalibrationDataReader:
    """CalibrationDataReader that loads samples from .npz files.

    Each .npz file contains multiple samples:
      sample{i}_input_{name}: input arrays
      sample{i}_output: reference output (not used for calibration, only for verification)
    """

    def __init__(self, npz_path, model_name, num_samples=8):
        self.model_name = model_name
        self.samples = []
        data = np.load(npz_path, allow_pickle=True)

        # Determine number of samples and input names
        sample_keys = [k for k in data.files if k.startswith('sample0_input_')]
        if not sample_keys:
            logger.warning(f"No sample0 inputs found in {npz_path}")
            return
        input_names = [k.replace('sample0_input_', '') for k in sample_keys]

        for idx in range(num_samples):
            prefix = f'sample{idx}_input_'
            input_keys = [k for k in data.files if k.startswith(prefix)]
            if not input_keys:
                break
            feeds = {}
            for k in input_keys:
                name = k.replace(prefix, '')
                feeds[name] = data[k]
            self.samples.append(feeds)

        logger.info(f"  Loaded {len(self.samples)} calibration samples from {npz_path}")
        logger.info(f"  Input names: {input_names}")

    def get_next(self):
        if not self.samples:
            return None
        return self.samples.pop(0)

    def rewind(self):
        # Reload samples (not implemented, caller should create new instance)
        pass


# ============================================================
# True FP16 conversion (without Olive, using onnxconverter_common)
# ============================================================

def convert_to_fp16_simple(input_path, output_path, keep_io_types=True,
                            op_block_list=None, node_block_list=None):
    """Convert FP32 ONNX to true FP16 using onnxconverter_common.

    This is the simplest approach: convert all float32 tensors to float16.
    Optionally keep input/output types as FP32 (keep_io_types=True) for
    API compatibility with FP32 callers.

    Args:
        op_block_list: list of op types to keep in FP32 (e.g., ['Range', 'Sqrt'])
        node_block_list: list of node names to keep in FP32
    """
    from onnxconverter_common.float16 import convert_float_to_float16

    logger.info(f"  Loading FP32 model: {input_path}")
    model = onnx.load(input_path, load_external_data=True)

    logger.info(f"  Converting to FP16 (keep_io_types={keep_io_types})...")
    if op_block_list:
        logger.info(f"  Op block list: {op_block_list}")
    if node_block_list:
        logger.info(f"  Node block list: {len(node_block_list)} nodes")

    model_fp16 = convert_float_to_float16(
        model,
        keep_io_types=keep_io_types,
        op_block_list=op_block_list or [],
        node_block_list=node_block_list or [],
        disable_shape_infer=False,
    )

    # Save with external data
    if os.path.exists(output_path):
        os.remove(output_path)
    data_path = output_path + '.data'
    if os.path.exists(data_path):
        os.remove(data_path)

    onnx.save_model(
        model_fp16, output_path,
        save_as_external_data=True,
        all_tensors_to_one_file=True,
        location=os.path.basename(output_path) + '.data',
        size_threshold=1024,
    )

    size_mb = os.path.getsize(output_path) / 1024 / 1024
    data_mb = os.path.getsize(data_path) / 1024 / 1024 if os.path.exists(data_path) else 0
    logger.info(f"  Saved: {output_path} ({size_mb:.1f}MB + {data_mb:.1f}MB data)")

    return model_fp16


def verify_fp16_model(model_path, calibration_data, model_name, max_samples=3):
    """Verify FP16 model by running calibration data and comparing with reference.

    Returns precision metrics (cos, SNR) averaged over samples.
    """
    import onnxruntime as ort

    logger.info(f"  Verifying {model_name} on {min(len(calibration_data), max_samples)} samples...")

    try:
        sess = ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])
    except Exception as e:
        logger.warning(f"  Failed to load FP16 model for verification: {e}")
        return None

    input_names = [inp.name for inp in sess.get_inputs()]
    input_types = {inp.name: inp.type for inp in sess.get_inputs()}

    metrics_list = []
    for idx, sample in enumerate(calibration_data[:max_samples]):
        feeds = {}
        for name, arr in sample.items():
            if name not in input_names:
                continue
            # Cast to FP16 if the model expects FP16 input
            if 'float16' in str(input_types.get(name, '')):
                feeds[name] = arr.astype(np.float16)
            else:
                feeds[name] = arr

        try:
            outputs = sess.run(None, feeds)
            metrics_list.append({'status': 'ok', 'output_shape': outputs[0].shape})
        except Exception as e:
            logger.warning(f"    Sample {idx}: inference failed - {str(e)[:100]}")
            metrics_list.append({'status': 'fail', 'error': str(e)[:100]})

    del sess
    return metrics_list


# ============================================================
# Per-model FP16 conversion with calibration-aware block lists
# ============================================================

def get_model_specific_block_list(model_name):
    """Return op/node block list for models with known sensitive operations.

    Some operations should stay FP32 for numerical stability:
    - Range: DML FP16 Range can produce NaN
    - Sqrt: precision-sensitive
    - ReduceMean: accumulation precision
    - LayerNormalization: precision-sensitive (but usually OK in FP16)
    """
    # Common block list for all models
    common_block = []

    if model_name == 'diff_step_dml':
        # diff_step has RoPE (Sin/Cos) and attention - keep Range in FP32
        # for DML stability
        return common_block + ['Range']
    elif model_name == 'mel_transform':
        # mel_transform has STFT + log + sqrt - precision sensitive
        return common_block + ['Sqrt', 'Log', 'Exp']
    elif model_name == 'vocoder_dml':
        # WARNING: vocoder TrueFP16 is NOT viable — see module docstring.
        # Blocking ISTFT/shape ops does NOT fix the ConvNeXt backbone tiny
        # weight values issue (20 matrices with min_positive ~4.83e-10).
        # This branch is reached only when VOCODER_SKIP=False (diagnostic use).
        # Production fp16/vocoder_dml.onnx is generated by convert_fp16_w16a32.py.
        # The istft_* initializers are kept FP32 by naming convention but this is
        # insufficient — see find_small_inits.py for the full list of broken weights.
        return common_block
    else:
        return common_block


def quantize_model(model_name, fp32_dir, output_dir, calib_dir):
    """Quantize a single model from FP32 to true FP16."""
    fp32_path = os.path.join(fp32_dir, model_name + '.onnx')
    output_path = os.path.join(output_dir, model_name + '.onnx')

    if not os.path.exists(fp32_path):
        logger.warning(f"  FP32 model not found: {fp32_path}")
        return False

    logger.info(f"\n{'='*60}")
    logger.info(f"Quantizing: {model_name}")
    logger.info(f"{'='*60}")

    fp32_size = os.path.getsize(fp32_path) / 1024 / 1024
    data_file = fp32_path + '.data'
    if os.path.exists(data_file):
        fp32_size += os.path.getsize(data_file) / 1024 / 1024
    logger.info(f"  FP32 size: {fp32_size:.1f} MB")

    # Get model-specific block list
    block_list = get_model_specific_block_list(model_name)
    if block_list:
        logger.info(f"  Sensitive ops kept FP32: {block_list}")

    # Convert to FP16
    try:
        convert_to_fp16_simple(
            fp32_path, output_path,
            keep_io_types=True,  # Keep FP32 I/O for API compatibility
            op_block_list=block_list,
        )
    except Exception as e:
        logger.error(f"  FP16 conversion failed: {e}")
        import traceback
        traceback.print_exc()
        return False

    # Verify with calibration data
    calib_path = os.path.join(calib_dir, model_name + '.npz')
    if os.path.exists(calib_path):
        data = np.load(calib_path, allow_pickle=True)
        calib_samples = []
        for idx in range(8):
            prefix = f'sample{idx}_input_'
            input_keys = [k for k in data.files if k.startswith(prefix)]
            if not input_keys:
                break
            feeds = {k.replace(prefix, ''): data[k] for k in input_keys}
            calib_samples.append(feeds)

        verify_fp16_model(output_path, calib_samples, model_name, max_samples=2)
    else:
        logger.warning(f"  No calibration data found at {calib_path}")

    # Check output
    fp16_size = os.path.getsize(output_path) / 1024 / 1024
    fp16_data = output_path + '.data'
    if os.path.exists(fp16_data):
        fp16_size += os.path.getsize(fp16_data) / 1024 / 1024
    ratio = fp16_size / fp32_size * 100 if fp32_size > 0 else 0
    logger.info(f"  FP16 size: {fp16_size:.1f} MB ({ratio:.1f}% of FP32)")

    return True


# ============================================================
# Olive DML optimization (apply to FP16 models)
# ============================================================

def apply_olive_dml_optimization(model_path, work_dir=None):
    """Apply Olive DML optimization passes to a model.

    Uses OnnxQuantizationPreprocess + OnnxPeepholeOptimizer + resolve_neg1.
    OnnxQuantizationPreprocess may fail for FP16 models with mixed types -
    if so, it is skipped and optimization continues with PeepholeOptimizer.
    """
    try:
        from olive.hardware.accelerator import AcceleratorSpec, Device
        from olive.hardware.constants import ExecutionProvider
        from olive.model import ONNXModelHandler
        from olive.passes.onnx.quantization import OnnxQuantizationPreprocess
        from olive.passes.onnx.peephole_optimizer import OnnxPeepholeOptimizer
    except ImportError as e:
        logger.warning(f"  Olive not available, skipping DML optimization: {e}")
        return False

    logger.info(f"  Applying Olive DML optimization...")

    accel_spec = AcceleratorSpec(
        accelerator_type=Device.GPU,
        execution_provider=ExecutionProvider.DmlExecutionProvider,
    )

    if work_dir is None:
        work_dir = model_path + '_olive_work'
    if os.path.exists(work_dir):
        shutil.rmtree(work_dir)
    os.makedirs(work_dir)

    try:
        model = ONNXModelHandler(model_path=model_path)

        # Step 1: OnnxQuantizationPreprocess (may fail for FP16 mixed types)
        preprocess_dir = os.path.join(work_dir, 'preprocessed')
        preprocess_config = OnnxQuantizationPreprocess.generate_config(
            accel_spec, {"skip_symbolic_shape": True}
        )
        preprocess_pass = OnnxQuantizationPreprocess(accel_spec, preprocess_config)
        try:
            model = preprocess_pass.run(model, preprocess_dir)
            logger.info(f"  OnnxQuantizationPreprocess completed")
        except Exception as e:
            err_str = str(e)
            if 'TypeInferenceError' in err_str or 'Inferred elem type' in err_str:
                logger.warning(f"  OnnxQuantizationPreprocess failed (shape inference): {err_str[:120]}")
                logger.warning(f"  Skipping preprocess, continuing with PeepholeOptimizer + resolve_neg1")
                model = ONNXModelHandler(model_path=model_path)
            else:
                raise

        # Step 2: OnnxPeepholeOptimizer
        # NOTE: cast_chain_elimination is DISABLED because it can remove
        # essential Cast nodes that maintain type consistency (especially
        # for keep_io_types=True where I/O is FP32 but internal ops are FP16).
        peephole_dir = os.path.join(work_dir, 'peephole')
        peephole_config = OnnxPeepholeOptimizer.generate_config(
            accel_spec,
            {
                "onnxscript_optimize": True,
                "onnxoptimizer_optimize": True,
                "fuse_reshape_operations": True,
                "cast_chain_elimination": False,
                "save_as_external_data": True,
                "all_tensors_to_one_file": True,
                "size_threshold": 1024,
            },
        )
        peephole_pass = OnnxPeepholeOptimizer(accel_spec, peephole_config)
        model = peephole_pass.run(model, peephole_dir)
        logger.info(f"  OnnxPeepholeOptimizer completed")

        # Step 3: resolve_neg1_in_reshape_shapes (DML compat)
        final_path_pre = model.model_path
        pre_proto = onnx.load(str(final_path_pre), load_external_data=True)
        try:
            pre_proto = shape_inference.infer_shapes(pre_proto)
        except Exception as e:
            logger.warning(f"  shape_inference failed (may be expected): {str(e)[:100]}")
        pre_proto = resolve_neg1_in_reshape_shapes(pre_proto)
        logger.info(f"  resolve_neg1_in_reshape_shapes completed")

        # Save final output with proper external data format
        # NOTE: Use onnx.save_model instead of shutil.copy2 to avoid file size doubling
        if os.path.exists(model_path):
            os.remove(model_path)
        old_data = model_path + '.data'
        if os.path.exists(old_data):
            os.remove(old_data)

        onnx.save_model(
            pre_proto,
            str(model_path),
            save_as_external_data=True,
            all_tensors_to_one_file=True,
            location=os.path.basename(model_path) + '.data',
            size_threshold=1024,
        )
        logger.info(f"  Olive optimization saved to: {model_path}")

    except Exception as e:
        logger.error(f"  Olive optimization failed: {e}")
        import traceback
        traceback.print_exc()
        return False
    finally:
        if os.path.exists(work_dir):
            shutil.rmtree(work_dir)

    return True


# ============================================================
# Main
# ============================================================

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Quantize FP32 ONNX to true FP16 with calibration')
    parser.add_argument('--fp32-dir', default=FP32_DIR,
                        help=f'FP32 models directory (default: {FP32_DIR})')
    parser.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR,
                        help=f'Output directory (default: {DEFAULT_OUTPUT_DIR})')
    parser.add_argument('--calib-dir', default=CALIB_DIR,
                        help=f'Calibration data directory (default: {CALIB_DIR})')
    parser.add_argument('--models', nargs='+', default=MODELS,
                        help='Models to quantize (default: all 9)')
    parser.add_argument('--skip-olive', action='store_true',
                        help='Skip Olive DML optimization')
    parser.add_argument('--skip-quantize', action='store_true',
                        help='Skip quantization (only run Olive on existing FP16)')
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    print("=" * 70)
    print("True FP16 Quantization Pipeline (with calibration)")
    print(f"FP32 source: {args.fp32_dir}")
    print(f"Output: {args.output_dir}")
    print(f"Calibration: {args.calib_dir}")
    print(f"Models: {args.models}")
    print(f"Olive DML optimization: {'SKIP' if args.skip_olive else 'ENABLED'}")
    print("=" * 70)

    results = {}

    for model_name in args.models:
        success = quantize_model(
            model_name, args.fp32_dir, args.output_dir, args.calib_dir
        )
        results[model_name] = {'quantize': 'OK' if success else 'FAIL'}

        if success and not args.skip_olive:
            model_path = os.path.join(args.output_dir, model_name + '.onnx')
            olive_ok = apply_olive_dml_optimization(model_path)
            results[model_name]['olive'] = 'OK' if olive_ok else 'SKIP'

    # Summary
    print(f"\n{'='*70}")
    print("SUMMARY")
    print(f"{'='*70}")
    print(f"{'Model':<25} {'Quantize':<12} {'Olive':<12}")
    print(f"{'-'*50}")
    for model_name, r in results.items():
        print(f"{model_name:<25} {r.get('quantize', 'N/A'):<12} {r.get('olive', 'N/A'):<12}")

    # Save report
    report_path = os.path.join(args.output_dir, 'quantization_report.json')
    with open(report_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\nReport saved: {report_path}")


if __name__ == '__main__':
    main()
