// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_CatalogModelInfo;
const __load_CatalogModelInfo = () => (__m_CatalogModelInfo ??= require('./CatalogModelInfo.js'));
const __get_CatalogModelInfo = () => __load_CatalogModelInfo().CatalogModelInfo;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const IID_ICatalogModelInstance = WinGuid.parse('9e920521-5e06-5c30-b0c2-8af313efb756');
const IID_CatalogModelInstance = WinGuid.parse('9e920521-5e06-5c30-b0c2-8af313efb756');

let _ICatalogModelInstanceCache;
const _ICatalogModelInstance = new Proxy({}, {
    get(_target, prop) {
        _ICatalogModelInstanceCache ??= DynWinRtType.registerInterface(
        "ICatalogModelInstance", IID_ICatalogModelInstance)
        .addMethod("get_ModelPaths", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("get_ModelInfo", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', DynWinRtType.interface(WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4')))));
        const value = _ICatalogModelInstanceCache[prop];
        return typeof value === 'function' ? value.bind(_ICatalogModelInstanceCache) : value;
    }
});

/**
 * Represents a locally available model instance and keeps it loaded while the object is alive.
 */
class CatalogModelInstance {
    _obj;

    constructor() {
        throw new TypeError('CatalogModelInstance cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(CatalogModelInstance.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_ICatalogModelInstance, 'CatalogModelInstance') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(CatalogModelInstance.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_ICatalogModelInstance, 'CatalogModelInstance') });
    }
    /**
     * Gets the local paths to the model files.
     */
    get modelPaths() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _ICatalogModelInstance.method(6); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets model information for this model instance.
     */
    get modelInfo() {
        return ((v) => v.isNull() ? null : (__get_CatalogModelInfo())._fromNative(v))((() => { const _m = _ICatalogModelInstance.method(7); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
}
exports.IID_CatalogModelInstance = IID_CatalogModelInstance;
exports.CatalogModelInstance = CatalogModelInstance;
