// Generated by dynwinrt-codegen — do not edit
import { DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_IKeyValuePair_String_String } from './IIterable_IKeyValuePair_String_String.js';
import { IVectorView_String } from './IVectorView_String.js';
import { CatalogModelInstanceResult } from './CatalogModelInstanceResult.js';
import { CatalogModelStatus } from './CatalogModelStatus.js';

/**
 * A WinRT async operation that supports progress reporting and cancellation.
 *
 * - `await op` — wait for the final result
 * - `op.progress(cb)` — receive incremental progress updates (chainable)
 * - `op.cancel()` — cancel the underlying WinRT operation
 */
type WinRTAsyncWithProgress<T, P = unknown> = Promise<T> & {
    /** Register a callback for progress updates. Returns `this` for chaining. */
    progress(cb: (value: P) => void): WinRTAsyncWithProgress<T, P>;
    /** Get the underlying Promise (equivalent to awaiting directly). */
    toPromise(): Promise<T>;
    /** Cancel the underlying WinRT async operation. */
    cancel(): void;
};

export declare const IID_CatalogModelInfo: WinGuid;
/**
 * Describes a model discovered from a model catalog.
 */
export declare class CatalogModelInfo {
    private constructor();
    /**
     * Gets the model's unique identifier within the catalog.
     */
    get id(): string;
    /**
     * Gets the model name.
     */
    get name(): string;
    /**
     * Gets the model publisher name.
     */
    get publisher(): string;
    /**
     * Gets the identifier of the catalog source that provided the model information.
     */
    get sourceId(): string;
    /**
     * Gets the model location, or the local cache location after the model has been downloaded.
     */
    get uri(): DynWinRtValue;
    /**
     * Gets the execution providers supported by the model.
     */
    get executionProviders(): IVectorView_String;
    /**
     * Gets the model size in bytes.
     */
    get modelSizeInBytes(): bigint;
    /**
     * Gets the model version.
     */
    get version(): string;
    /**
     * Gets the model license identifier or description.
     */
    get license(): string;
    /**
     * Gets the URI to the model license document.
     */
    get licenseUri(): string;
    /**
     * Gets the model license text.
     */
    get licenseText(): string;
    /**
     * Gets the current model status.
     * @returns The current model status.
     */
    getStatus(): CatalogModelStatus;
    /**
     * Gets an instance of the model, downloading it first if necessary.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports acquisition progress and returns the model instance result.
     */
    getInstanceAsync(signal?: AbortSignal): WinRTAsyncWithProgress<CatalogModelInstanceResult, number>;
    /**
     * Gets an instance of the model using additional request headers, downloading it first if necessary.
     * @param additionalHeaders Additional headers to include when accessing remote catalog or model content.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports acquisition progress and returns the model instance result.
     */
    getInstanceAsync(additionalHeaders: IIterable_IKeyValuePair_String_String, signal?: AbortSignal): WinRTAsyncWithProgress<CatalogModelInstanceResult, number>;
}
