// Generated by dynwinrt-codegen — do not edit

/**
 * Indicates whether a catalog model instance is available on the local system.
 */
const CatalogModelInstanceStatus = Object.freeze({
    /**
     * The model instance is available and downloaded.
     */
    Available: 0,
    /**
     * The model instance is being downloaded or installed.
     */
    InProgress: 1,
    /**
     * The model instance is not available locally.
     */
    Unavailable: 2,
});
exports.CatalogModelInstanceStatus = CatalogModelInstanceStatus;
