// Generated by dynwinrt-codegen — do not edit
/**
 * Indicates whether a catalog model is ready for use.
 */
export type CatalogModelStatus = (typeof CatalogModelStatus)[keyof typeof CatalogModelStatus];
export declare const CatalogModelStatus: {
    /**
     * The model is ready for use.
     */
    readonly Ready: 0;
    /**
     * The model is not ready for use.
     */
    readonly NotReady: 1;
};
