// Generated by dynwinrt-codegen — do not edit

/**
 * Indicates whether a catalog model is ready for use.
 */
const CatalogModelStatus = Object.freeze({
    /**
     * The model is ready for use.
     */
    Ready: 0,
    /**
     * The model is not ready for use.
     */
    NotReady: 1,
});
exports.CatalogModelStatus = CatalogModelStatus;
