// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_String } from './IVectorView_String.js';
import { CatalogModelInfo } from './CatalogModelInfo.js';

export declare const IID_CatalogModelInstance: WinGuid;
/**
 * Represents a locally available model instance and keeps it loaded while the object is alive.
 */
export declare class CatalogModelInstance {
    private constructor();
    /**
     * Gets the local paths to the model files.
     */
    get modelPaths(): IVectorView_String;
    /**
     * Gets model information for this model instance.
     */
    get modelInfo(): CatalogModelInfo;
}
