// Generated by dynwinrt-codegen — do not edit
import { DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';
import { CatalogModelInstance } from './CatalogModelInstance.js';
import { CatalogModelInstanceStatus } from './CatalogModelInstanceStatus.js';

export declare const IID_CatalogModelInstanceResult: WinGuid;
/**
 * Contains the result of a model acquisition operation.
 */
export declare class CatalogModelInstanceResult {
    private constructor();
    /**
     * Gets the model instance status.
     */
    get status(): CatalogModelInstanceStatus;
    /**
     * Gets the error code returned when model acquisition fails.
     */
    get extendedError(): DynWinRtValue;
    /**
     * Gets diagnostic text that can help developers understand the model state.
     */
    get diagnosticText(): string;
    /**
     * Gets the acquired model instance.
     * @returns The acquired model instance, or null if no instance is available.
     */
    getInstance(): CatalogModelInstance;
}
