// Generated by dynwinrt-codegen — do not edit
/**
 * Indicates whether a catalog model instance is available on the local system.
 */
export type CatalogModelInstanceStatus = (typeof CatalogModelInstanceStatus)[keyof typeof CatalogModelInstanceStatus];
export declare const CatalogModelInstanceStatus: {
    /**
     * The model instance is available and downloaded.
     */
    readonly Available: 0;
    /**
     * The model instance is being downloaded or installed.
     */
    readonly InProgress: 1;
    /**
     * The model instance is not available locally.
     */
    readonly Unavailable: 2;
};
