// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_CatalogModelInstanceResult;
const __load_CatalogModelInstanceResult = () => (__m_CatalogModelInstanceResult ??= require('./CatalogModelInstanceResult.js'));
const __get_CatalogModelInstanceResult = () => __load_CatalogModelInstanceResult().CatalogModelInstanceResult;
let __m_CatalogModelStatus;
const __load_CatalogModelStatus = () => (__m_CatalogModelStatus ??= require('./CatalogModelStatus.js'));
const __get_CatalogModelStatus = () => __load_CatalogModelStatus().CatalogModelStatus;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_ICatalogModelInfo = WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4');
const IID_CatalogModelInfo = WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4');

let _ICatalogModelInfoCache;
const _ICatalogModelInfo = new Proxy({}, {
    get(_target, prop) {
        _ICatalogModelInfoCache ??= DynWinRtType.registerInterface(
        "ICatalogModelInfo", IID_ICatalogModelInfo)
        .addMethod("get_Id", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Publisher", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_SourceId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Uri", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("get_ExecutionProviders", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("get_ModelSizeInBytes", new DynWinRtMethodSig().addOut(DynWinRtType.u64()))
        .addMethod("get_Version", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_License", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_LicenseUri", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_LicenseText", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("GetStatus", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.MachineLearning.CatalogModelStatus', ['Ready', 'NotReady'], [0, 1])))
        .addMethod("GetInstanceAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInstanceResult', DynWinRtType.interface(WinGuid.parse('b3701b71-61fa-5185-a2ce-8df6e6a5c66d'))), DynWinRtType.f64())))
        .addMethod("GetInstanceAsync2", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInstanceResult', DynWinRtType.interface(WinGuid.parse('b3701b71-61fa-5185-a2ce-8df6e6a5c66d'))), DynWinRtType.f64())));
        const value = _ICatalogModelInfoCache[prop];
        return typeof value === 'function' ? value.bind(_ICatalogModelInfoCache) : value;
    }
});

/**
 * Describes a model discovered from a model catalog.
 */
class CatalogModelInfo {
    _obj;

    constructor() {
        throw new TypeError('CatalogModelInfo cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(CatalogModelInfo.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_ICatalogModelInfo, 'CatalogModelInfo') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(CatalogModelInfo.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_ICatalogModelInfo, 'CatalogModelInfo') });
    }
    /**
     * Gets the model's unique identifier within the catalog.
     */
    get id() {
        return (() => { const _m = _ICatalogModelInfo.method(6); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(6).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the model name.
     */
    get name() {
        return (() => { const _m = _ICatalogModelInfo.method(7); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(7).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the model publisher name.
     */
    get publisher() {
        return (() => { const _m = _ICatalogModelInfo.method(8); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(8).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the identifier of the catalog source that provided the model information.
     */
    get sourceId() {
        return (() => { const _m = _ICatalogModelInfo.method(9); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(9).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the model location, or the local cache location after the model has been downloaded.
     */
    get uri() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _ICatalogModelInfo.method(10); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets the execution providers supported by the model.
     */
    get executionProviders() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _ICatalogModelInfo.method(11); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets the model size in bytes.
     */
    get modelSizeInBytes() {
        return _ICatalogModelInfo.method(12).invoke(this._obj, []).toU64Bigint();
    }
    /**
     * Gets the model version.
     */
    get version() {
        return (() => { const _m = _ICatalogModelInfo.method(13); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(13).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the model license identifier or description.
     */
    get license() {
        return (() => { const _m = _ICatalogModelInfo.method(14); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(14).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the URI to the model license document.
     */
    get licenseUri() {
        return (() => { const _m = _ICatalogModelInfo.method(15); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(15).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the model license text.
     */
    get licenseText() {
        return (() => { const _m = _ICatalogModelInfo.method(16); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInfo.method(16).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the current model status.
     * @returns The current model status.
     */
    getStatus() {
        return _ICatalogModelInfo.method(17).invoke(this._obj, []).toNumber();
    }
    _getInstanceAsync_1(signal) {
        if (signal?.aborted) {
            const _rej = Promise.reject(signal.reason);
            _rej.catch(() => {});
            return Object.assign(_rej, {
                progress(_cb) { return this; },
                toPromise() { const _p = Promise.reject(signal.reason); _p.catch(() => {}); return _p; },
                cancel() {},
            });
        }
        const _op = _ICatalogModelInfo.method(18).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        const _wrap = (p) => p.then((_v) => ((v) => v.isNull() ? null : (__get_CatalogModelInstanceResult())._fromNative(v))(_v), (_e) => { if (signal?.aborted) throw signal.reason; throw _e; }).finally(() => { if (_onAbort) signal.removeEventListener('abort', _onAbort); });
        const _promise = _wrap(_op.toPromise());
        return Object.assign(_promise, {
            progress(cb) { _op.onProgress((_p) => cb(_p.toF64())); return this; },
            toPromise() { return _wrap(_op.toPromise()); },
            cancel() { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } },
        });
    }
    _getInstanceAsync_2(additionalHeaders, signal) {
        if (signal?.aborted) {
            const _rej = Promise.reject(signal.reason);
            _rej.catch(() => {});
            return Object.assign(_rej, {
                progress(_cb) { return this; },
                toPromise() { const _p = Promise.reject(signal.reason); _p.catch(() => {}); return _p; },
                cancel() {},
            });
        }
        const _op = _ICatalogModelInfo.method(19).invoke(this._obj, [_unwrap(additionalHeaders)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        const _wrap = (p) => p.then((_v) => ((v) => v.isNull() ? null : (__get_CatalogModelInstanceResult())._fromNative(v))(_v), (_e) => { if (signal?.aborted) throw signal.reason; throw _e; }).finally(() => { if (_onAbort) signal.removeEventListener('abort', _onAbort); });
        const _promise = _wrap(_op.toPromise());
        return Object.assign(_promise, {
            progress(cb) { _op.onProgress((_p) => cb(_p.toF64())); return this; },
            toPromise() { return _wrap(_op.toPromise()); },
            cancel() { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } },
        });
    }
    /**
     * Gets an instance of the model, downloading it first if necessary.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports acquisition progress and returns the model instance result.
     */
    getInstanceAsync(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._getInstanceAsync_2(args[0], args[1]);
        }
        return this._getInstanceAsync_1(args[0]);
    }
}
exports.IID_CatalogModelInfo = IID_CatalogModelInfo;
exports.CatalogModelInfo = CatalogModelInfo;
