// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_CatalogModelInstance;
const __load_CatalogModelInstance = () => (__m_CatalogModelInstance ??= require('./CatalogModelInstance.js'));
const __get_CatalogModelInstance = () => __load_CatalogModelInstance().CatalogModelInstance;
let __m_CatalogModelInstanceStatus;
const __load_CatalogModelInstanceStatus = () => (__m_CatalogModelInstanceStatus ??= require('./CatalogModelInstanceStatus.js'));
const __get_CatalogModelInstanceStatus = () => __load_CatalogModelInstanceStatus().CatalogModelInstanceStatus;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const IID_ICatalogModelInstanceResult = WinGuid.parse('b3701b71-61fa-5185-a2ce-8df6e6a5c66d');
const IID_CatalogModelInstanceResult = WinGuid.parse('b3701b71-61fa-5185-a2ce-8df6e6a5c66d');

let _ICatalogModelInstanceResultCache;
const _ICatalogModelInstanceResult = new Proxy({}, {
    get(_target, prop) {
        _ICatalogModelInstanceResultCache ??= DynWinRtType.registerInterface(
        "ICatalogModelInstanceResult", IID_ICatalogModelInstanceResult)
        .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.MachineLearning.CatalogModelInstanceStatus', ['Available', 'InProgress', 'Unavailable'], [0, 1, 2])))
        .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("get_DiagnosticText", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("GetInstance", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInstance', DynWinRtType.interface(WinGuid.parse('9e920521-5e06-5c30-b0c2-8af313efb756')))));
        const value = _ICatalogModelInstanceResultCache[prop];
        return typeof value === 'function' ? value.bind(_ICatalogModelInstanceResultCache) : value;
    }
});

/**
 * Contains the result of a model acquisition operation.
 */
class CatalogModelInstanceResult {
    _obj;

    constructor() {
        throw new TypeError('CatalogModelInstanceResult cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(CatalogModelInstanceResult.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_ICatalogModelInstanceResult, 'CatalogModelInstanceResult') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(CatalogModelInstanceResult.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_ICatalogModelInstanceResult, 'CatalogModelInstanceResult') });
    }
    /**
     * Gets the model instance status.
     */
    get status() {
        return (() => { const _m = _ICatalogModelInstanceResult.method(6); return typeof _m.getI32 === 'function' ? _m.getI32(this._obj) : _ICatalogModelInstanceResult.method(6).invoke(this._obj, []).toNumber(); })();
    }
    /**
     * Gets the error code returned when model acquisition fails.
     */
    get extendedError() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _ICatalogModelInstanceResult.method(7); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets diagnostic text that can help developers understand the model state.
     */
    get diagnosticText() {
        return (() => { const _m = _ICatalogModelInstanceResult.method(8); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _ICatalogModelInstanceResult.method(8).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the acquired model instance.
     * @returns The acquired model instance, or null if no instance is available.
     */
    getInstance() {
        return ((v) => v.isNull() ? null : (__get_CatalogModelInstance())._fromNative(v))(_ICatalogModelInstanceResult.method(9).invoke(this._obj, []));
    }
}
exports.IID_CatalogModelInstanceResult = IID_CatalogModelInstanceResult;
exports.CatalogModelInstanceResult = CatalogModelInstanceResult;
