// Generated by dynwinrt-codegen — do not edit

/**
 * Indicates the status of an execution provider readiness operation.
 */
const ExecutionProviderReadyResultState = Object.freeze({
    /**
     * The execution provider is transitioning to the ready state, such as while being acquired or installed.
     */
    InProgress: 0,
    /**
     * The execution provider is ready for use.
     */
    Success: 1,
    /**
     * The execution provider failed to become ready.
     */
    Failure: 2,
});
exports.ExecutionProviderReadyResultState = ExecutionProviderReadyResultState;
