// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_ExecutionProviderReadyResultState;
const __load_ExecutionProviderReadyResultState = () => (__m_ExecutionProviderReadyResultState ??= require('./ExecutionProviderReadyResultState.js'));
const __get_ExecutionProviderReadyResultState = () => __load_ExecutionProviderReadyResultState().ExecutionProviderReadyResultState;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const IID_IExecutionProviderReadyResult = WinGuid.parse('91c1724d-93c7-5284-adbe-ba2bd7be7c79');
const IID_ExecutionProviderReadyResult = WinGuid.parse('91c1724d-93c7-5284-adbe-ba2bd7be7c79');

let _IExecutionProviderReadyResultCache;
const _IExecutionProviderReadyResult = new Proxy({}, {
    get(_target, prop) {
        _IExecutionProviderReadyResultCache ??= DynWinRtType.registerInterface(
        "IExecutionProviderReadyResult", IID_IExecutionProviderReadyResult)
        .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResultState', ['InProgress', 'Success', 'Failure'], [0, 1, 2])))
        .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("get_DiagnosticText", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));
        const value = _IExecutionProviderReadyResultCache[prop];
        return typeof value === 'function' ? value.bind(_IExecutionProviderReadyResultCache) : value;
    }
});

/**
 * Contains the result of an operation that prepares an execution provider for use.
 */
class ExecutionProviderReadyResult {
    _obj;

    constructor() {
        throw new TypeError('ExecutionProviderReadyResult cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(ExecutionProviderReadyResult.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_IExecutionProviderReadyResult, 'ExecutionProviderReadyResult') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(ExecutionProviderReadyResult.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_IExecutionProviderReadyResult, 'ExecutionProviderReadyResult') });
    }
    /**
     * Gets the status of the readiness operation.
     */
    get status() {
        return (() => { const _m = _IExecutionProviderReadyResult.method(6); return typeof _m.getI32 === 'function' ? _m.getI32(this._obj) : _IExecutionProviderReadyResult.method(6).invoke(this._obj, []).toNumber(); })();
    }
    /**
     * Gets the error code returned when the readiness operation fails.
     */
    get extendedError() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _IExecutionProviderReadyResult.method(7); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets diagnostic text that can help developers understand the execution provider state.
     */
    get diagnosticText() {
        return (() => { const _m = _IExecutionProviderReadyResult.method(8); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _IExecutionProviderReadyResult.method(8).invoke(this._obj, []).toString(); })();
    }
}
exports.IID_ExecutionProviderReadyResult = IID_ExecutionProviderReadyResult;
exports.ExecutionProviderReadyResult = ExecutionProviderReadyResult;
