// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_ExecutionProviderCertification;
const __load_ExecutionProviderCertification = () => (__m_ExecutionProviderCertification ??= require('./ExecutionProviderCertification.js'));
const __get_ExecutionProviderCertification = () => __load_ExecutionProviderCertification().ExecutionProviderCertification;
let __m_ExecutionProviderReadyResult;
const __load_ExecutionProviderReadyResult = () => (__m_ExecutionProviderReadyResult ??= require('./ExecutionProviderReadyResult.js'));
const __get_ExecutionProviderReadyResult = () => __load_ExecutionProviderReadyResult().ExecutionProviderReadyResult;
let __m_ExecutionProviderReadyState;
const __load_ExecutionProviderReadyState = () => (__m_ExecutionProviderReadyState ??= require('./ExecutionProviderReadyState.js'));
const __get_ExecutionProviderReadyState = () => __load_ExecutionProviderReadyState().ExecutionProviderReadyState;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const IID_IExecutionProvider = WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff');
const IID_ExecutionProvider = WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff');

let _IExecutionProviderCache;
const _IExecutionProvider = new Proxy({}, {
    get(_target, prop) {
        _IExecutionProviderCache ??= DynWinRtType.registerInterface(
        "IExecutionProvider", IID_IExecutionProvider)
        .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_LibraryPath", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_PackageId", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("get_ReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyState', ['Ready', 'NotReady', 'NotPresent'], [0, 1, 2])))
        .addMethod("get_Certification", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.MachineLearning.ExecutionProviderCertification', ['Unknown', 'Certified', 'Uncertified'], [0, 1, 2])))
        .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResult', DynWinRtType.interface(WinGuid.parse('91c1724d-93c7-5284-adbe-ba2bd7be7c79'))), DynWinRtType.f64())))
        .addMethod("TryRegister", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));
        const value = _IExecutionProviderCache[prop];
        return typeof value === 'function' ? value.bind(_IExecutionProviderCache) : value;
    }
});

/**
 * Represents an execution provider package that can be used by ONNX Runtime through Windows ML.
 */
class ExecutionProvider {
    _obj;

    constructor() {
        throw new TypeError('ExecutionProvider cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(ExecutionProvider.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_IExecutionProvider, 'ExecutionProvider') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(ExecutionProvider.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_IExecutionProvider, 'ExecutionProvider') });
    }
    /**
     * Gets the execution provider name as registered with ONNX Runtime.
     */
    get name() {
        return (() => { const _m = _IExecutionProvider.method(6); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _IExecutionProvider.method(6).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the absolute path to the execution provider library when the provider is ready for use.
     */
    get libraryPath() {
        return (() => { const _m = _IExecutionProvider.method(7); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _IExecutionProvider.method(7).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets package identity information for the execution provider package.
     */
    get packageId() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _IExecutionProvider.method(8); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets the current readiness state of the execution provider in the current process.
     */
    get readyState() {
        return (() => { const _m = _IExecutionProvider.method(9); return typeof _m.getI32 === 'function' ? _m.getI32(this._obj) : _IExecutionProvider.method(9).invoke(this._obj, []).toNumber(); })();
    }
    /**
     * Gets the certification state of the execution provider.
     */
    get certification() {
        return (() => { const _m = _IExecutionProvider.method(10); return typeof _m.getI32 === 'function' ? _m.getI32(this._obj) : _IExecutionProvider.method(10).invoke(this._obj, []).toNumber(); })();
    }
    /**
     * Makes the execution provider available to the current process, acquiring and installing the associated package if necessary.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports readiness progress and returns the readiness result.
     */
    ensureReadyAsync(signal) {
        if (signal?.aborted) {
            const _rej = Promise.reject(signal.reason);
            _rej.catch(() => {});
            return Object.assign(_rej, {
                progress(_cb) { return this; },
                toPromise() { const _p = Promise.reject(signal.reason); _p.catch(() => {}); return _p; },
                cancel() {},
            });
        }
        const _op = _IExecutionProvider.method(11).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        const _wrap = (p) => p.then((_v) => ((v) => v.isNull() ? null : (__get_ExecutionProviderReadyResult())._fromNative(v))(_v), (_e) => { if (signal?.aborted) throw signal.reason; throw _e; }).finally(() => { if (_onAbort) signal.removeEventListener('abort', _onAbort); });
        const _promise = _wrap(_op.toPromise());
        return Object.assign(_promise, {
            progress(cb) { _op.onProgress((_p) => cb(_p.toF64())); return this; },
            toPromise() { return _wrap(_op.toPromise()); },
            cancel() { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } },
        });
    }
    /**
     * Registers the execution provider with ONNX Runtime so it can be selected for model execution.
     * @returns True if the provider was registered successfully; otherwise, false.
     */
    tryRegister() {
        return _IExecutionProvider.method(12).invoke(this._obj, []).toBool();
    }
}
exports.IID_ExecutionProvider = IID_ExecutionProvider;
exports.ExecutionProvider = ExecutionProvider;
