// Generated by dynwinrt-codegen — do not edit
/**
 * Indicates the certification state of an execution provider for Windows ML.
 */
export type ExecutionProviderCertification = (typeof ExecutionProviderCertification)[keyof typeof ExecutionProviderCertification];
export declare const ExecutionProviderCertification: {
    /**
     * The execution provider certification state is not known.
     */
    readonly Unknown: 0;
    /**
     * The execution provider is certified for use with Windows ML.
     */
    readonly Certified: 1;
    /**
     * The execution provider is not certified for use with Windows ML.
     */
    readonly Uncertified: 2;
};
