// Generated by dynwinrt-codegen — do not edit

/**
 * Indicates whether an execution provider is available for use by ONNX Runtime in the current process.
 */
const ExecutionProviderReadyState = Object.freeze({
    /**
     * The execution provider is ready to be used with ONNX Runtime in the current process.
     */
    Ready: 0,
    /**
     * The execution provider is present but is not ready to be used with ONNX Runtime in the current process.
     */
    NotReady: 1,
    /**
     * The execution provider is not present on the system, but can be acquired.
     */
    NotPresent: 2,
});
exports.ExecutionProviderReadyState = ExecutionProviderReadyState;
