// Generated by dynwinrt-codegen — do not edit
import { DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';
import { ExecutionProviderReadyResultState } from './ExecutionProviderReadyResultState.js';

export declare const IID_ExecutionProviderReadyResult: WinGuid;
/**
 * Contains the result of an operation that prepares an execution provider for use.
 */
export declare class ExecutionProviderReadyResult {
    private constructor();
    /**
     * Gets the status of the readiness operation.
     */
    get status(): ExecutionProviderReadyResultState;
    /**
     * Gets the error code returned when the readiness operation fails.
     */
    get extendedError(): DynWinRtValue;
    /**
     * Gets diagnostic text that can help developers understand the execution provider state.
     */
    get diagnosticText(): string;
}
