// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IVector_ExecutionProvider } from './IVector_ExecutionProvider.js';
import { ExecutionProvider } from './ExecutionProvider.js';

/**
 * A WinRT async operation that supports progress reporting and cancellation.
 *
 * - `await op` — wait for the final result
 * - `op.progress(cb)` — receive incremental progress updates (chainable)
 * - `op.cancel()` — cancel the underlying WinRT operation
 */
type WinRTAsyncWithProgress<T, P = unknown> = Promise<T> & {
    /** Register a callback for progress updates. Returns `this` for chaining. */
    progress(cb: (value: P) => void): WinRTAsyncWithProgress<T, P>;
    /** Get the underlying Promise (equivalent to awaiting directly). */
    toPromise(): Promise<T>;
    /** Cancel the underlying WinRT async operation. */
    cancel(): void;
};

export declare const IID_ExecutionProviderCatalog: WinGuid;
/**
 * Provides access to execution providers that are compatible with the current system.
 */
export declare class ExecutionProviderCatalog {
    private constructor();
    /**
     * Gets the default execution provider catalog for the current system.
     * @returns The default execution provider catalog, or null if the catalog is not available.
     */
    static getDefault(): ExecutionProviderCatalog;
    /**
     * Returns all execution providers compatible with the current hardware.
     * @returns The compatible execution providers.
     */
    findAllProviders(): ExecutionProvider[];
    /**
     * Acquires, prepares, and registers certified execution providers in the catalog with ONNX Runtime.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports progress and returns the providers that were registered successfully.
     */
    ensureAndRegisterCertifiedAsync(signal?: AbortSignal): WinRTAsyncWithProgress<IVector_ExecutionProvider, number>;
    /**
     * Registers certified execution providers that are already present and ready to use with ONNX Runtime.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports progress and returns the providers that were registered successfully.
     */
    registerCertifiedAsync(signal?: AbortSignal): WinRTAsyncWithProgress<IVector_ExecutionProvider, number>;
}
