// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_ExecutionProvider;
const __load_ExecutionProvider = () => (__m_ExecutionProvider ??= require('./ExecutionProvider.js'));
const __get_ExecutionProvider = () => __load_ExecutionProvider().ExecutionProvider;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const IID_IExecutionProviderCatalog = WinGuid.parse('aa9bfe14-2222-5921-8002-4d2a205ea03c');
const IID_IExecutionProviderCatalogStatics = WinGuid.parse('550def98-2611-5433-afb8-43673b610848');
const IID_ExecutionProviderCatalog = WinGuid.parse('aa9bfe14-2222-5921-8002-4d2a205ea03c');

let _IExecutionProviderCatalogCache;
const _IExecutionProviderCatalog = new Proxy({}, {
    get(_target, prop) {
        _IExecutionProviderCatalogCache ??= DynWinRtType.registerInterface(
        "IExecutionProviderCatalog", IID_IExecutionProviderCatalog)
        .addMethod("FindAllProviders", new DynWinRtMethodSig().addOut(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', DynWinRtType.interface(WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))))))
        .addMethod("EnsureAndRegisterCertifiedAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.object(), DynWinRtType.f64())))
        .addMethod("RegisterCertifiedAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.object(), DynWinRtType.f64())));
        const value = _IExecutionProviderCatalogCache[prop];
        return typeof value === 'function' ? value.bind(_IExecutionProviderCatalogCache) : value;
    }
});

let _IExecutionProviderCatalogStaticsCache;
const _IExecutionProviderCatalogStatics = new Proxy({}, {
    get(_target, prop) {
        _IExecutionProviderCatalogStaticsCache ??= DynWinRtType.registerInterface(
        "IExecutionProviderCatalogStatics", IID_IExecutionProviderCatalogStatics)
        .addMethod("GetDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog', DynWinRtType.interface(WinGuid.parse('aa9bfe14-2222-5921-8002-4d2a205ea03c')))));
        const value = _IExecutionProviderCatalogStaticsCache[prop];
        return typeof value === 'function' ? value.bind(_IExecutionProviderCatalogStaticsCache) : value;
    }
});

/**
 * Provides access to execution providers that are compatible with the current system.
 */
class ExecutionProviderCatalog {
    _obj;
    static _s_IExecutionProviderCatalogStatics;
    static s_IExecutionProviderCatalogStatics() { return ExecutionProviderCatalog._s_IExecutionProviderCatalogStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog').cast(IID_IExecutionProviderCatalogStatics); }

    constructor() {
        throw new TypeError('ExecutionProviderCatalog cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(ExecutionProviderCatalog.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_IExecutionProviderCatalog, 'ExecutionProviderCatalog') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(ExecutionProviderCatalog.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_IExecutionProviderCatalog, 'ExecutionProviderCatalog') });
    }
    /**
     * Gets the default execution provider catalog for the current system.
     * @returns The default execution provider catalog, or null if the catalog is not available.
     */
    static getDefault() {
        return ((v) => v.isNull() ? null : ExecutionProviderCatalog._fromNative(v))(_IExecutionProviderCatalogStatics.method(6).invoke(ExecutionProviderCatalog.s_IExecutionProviderCatalogStatics(), []));
    }
    /**
     * Returns all execution providers compatible with the current hardware.
     * @returns The compatible execution providers.
     */
    findAllProviders() {
        return _IExecutionProviderCatalog.method(6).invoke(this._obj, []).asArray().toValues().map(v => v.isNull() ? null : (__get_ExecutionProvider())._fromNative(v));
    }
    /**
     * Acquires, prepares, and registers certified execution providers in the catalog with ONNX Runtime.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports progress and returns the providers that were registered successfully.
     */
    ensureAndRegisterCertifiedAsync(signal) {
        if (signal?.aborted) {
            const _rej = Promise.reject(signal.reason);
            _rej.catch(() => {});
            return Object.assign(_rej, {
                progress(_cb) { return this; },
                toPromise() { const _p = Promise.reject(signal.reason); _p.catch(() => {}); return _p; },
                cancel() {},
            });
        }
        const _op = _IExecutionProviderCatalog.method(7).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        const _wrap = (p) => p.then((_v) => ((v) => v.isNull() ? null : v)(_v), (_e) => { if (signal?.aborted) throw signal.reason; throw _e; }).finally(() => { if (_onAbort) signal.removeEventListener('abort', _onAbort); });
        const _promise = _wrap(_op.toPromise());
        return Object.assign(_promise, {
            progress(cb) { _op.onProgress((_p) => cb(_p.toF64())); return this; },
            toPromise() { return _wrap(_op.toPromise()); },
            cancel() { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } },
        });
    }
    /**
     * Registers certified execution providers that are already present and ready to use with ONNX Runtime.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports progress and returns the providers that were registered successfully.
     */
    registerCertifiedAsync(signal) {
        if (signal?.aborted) {
            const _rej = Promise.reject(signal.reason);
            _rej.catch(() => {});
            return Object.assign(_rej, {
                progress(_cb) { return this; },
                toPromise() { const _p = Promise.reject(signal.reason); _p.catch(() => {}); return _p; },
                cancel() {},
            });
        }
        const _op = _IExecutionProviderCatalog.method(8).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        const _wrap = (p) => p.then((_v) => ((v) => v.isNull() ? null : v)(_v), (_e) => { if (signal?.aborted) throw signal.reason; throw _e; }).finally(() => { if (_onAbort) signal.removeEventListener('abort', _onAbort); });
        const _promise = _wrap(_op.toPromise());
        return Object.assign(_promise, {
            progress(cb) { _op.onProgress((_p) => cb(_p.toF64())); return this; },
            toPromise() { return _wrap(_op.toPromise()); },
            cancel() { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } },
        });
    }
}
exports.IID_ExecutionProviderCatalog = IID_ExecutionProviderCatalog;
exports.ExecutionProviderCatalog = ExecutionProviderCatalog;
