// Generated by dynwinrt-codegen — do not edit
/**
 * Indicates whether an execution provider is available for use by ONNX Runtime in the current process.
 */
export type ExecutionProviderReadyState = (typeof ExecutionProviderReadyState)[keyof typeof ExecutionProviderReadyState];
export declare const ExecutionProviderReadyState: {
    /**
     * The execution provider is ready to be used with ONNX Runtime in the current process.
     */
    readonly Ready: 0;
    /**
     * The execution provider is present but is not ready to be used with ONNX Runtime in the current process.
     */
    readonly NotReady: 1;
    /**
     * The execution provider is not present on the system, but can be acquired.
     */
    readonly NotPresent: 2;
};
