// Generated by dynwinrt-codegen — do not edit

/**
 * Indicates the certification state of an execution provider for Windows ML.
 */
const ExecutionProviderCertification = Object.freeze({
    /**
     * The execution provider certification state is not known.
     */
    Unknown: 0,
    /**
     * The execution provider is certified for use with Windows ML.
     */
    Certified: 1,
    /**
     * The execution provider is not certified for use with Windows ML.
     */
    Uncertified: 2,
});
exports.ExecutionProviderCertification = ExecutionProviderCertification;
