// Generated by dynwinrt-codegen — do not edit
import { DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';
import { ExecutionProviderCertification } from './ExecutionProviderCertification.js';
import { ExecutionProviderReadyResult } from './ExecutionProviderReadyResult.js';
import { ExecutionProviderReadyState } from './ExecutionProviderReadyState.js';

/**
 * A WinRT async operation that supports progress reporting and cancellation.
 *
 * - `await op` — wait for the final result
 * - `op.progress(cb)` — receive incremental progress updates (chainable)
 * - `op.cancel()` — cancel the underlying WinRT operation
 */
type WinRTAsyncWithProgress<T, P = unknown> = Promise<T> & {
    /** Register a callback for progress updates. Returns `this` for chaining. */
    progress(cb: (value: P) => void): WinRTAsyncWithProgress<T, P>;
    /** Get the underlying Promise (equivalent to awaiting directly). */
    toPromise(): Promise<T>;
    /** Cancel the underlying WinRT async operation. */
    cancel(): void;
};

export declare const IID_ExecutionProvider: WinGuid;
/**
 * Represents an execution provider package that can be used by ONNX Runtime through Windows ML.
 */
export declare class ExecutionProvider {
    private constructor();
    /**
     * Gets the execution provider name as registered with ONNX Runtime.
     */
    get name(): string;
    /**
     * Gets the absolute path to the execution provider library when the provider is ready for use.
     */
    get libraryPath(): string;
    /**
     * Gets package identity information for the execution provider package.
     */
    get packageId(): DynWinRtValue;
    /**
     * Gets the current readiness state of the execution provider in the current process.
     */
    get readyState(): ExecutionProviderReadyState;
    /**
     * Gets the certification state of the execution provider.
     */
    get certification(): ExecutionProviderCertification;
    /**
     * Makes the execution provider available to the current process, acquiring and installing the associated package if necessary.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that reports readiness progress and returns the readiness result.
     */
    ensureReadyAsync(signal?: AbortSignal): WinRTAsyncWithProgress<ExecutionProviderReadyResult, number>;
    /**
     * Registers the execution provider with ONNX Runtime so it can be selected for model execution.
     * @returns True if the provider was registered successfully; otherwise, false.
     */
    tryRegister(): boolean;
}
