// Generated by dynwinrt-codegen — do not edit
/**
 * Indicates the status of an execution provider readiness operation.
 */
export type ExecutionProviderReadyResultState = (typeof ExecutionProviderReadyResultState)[keyof typeof ExecutionProviderReadyResultState];
export declare const ExecutionProviderReadyResultState: {
    /**
     * The execution provider is transitioning to the ready state, such as while being acquired or installed.
     */
    readonly InProgress: 0;
    /**
     * The execution provider is ready for use.
     */
    readonly Success: 1;
    /**
     * The execution provider failed to become ready.
     */
    readonly Failure: 2;
};
