// Generated by dynwinrt-codegen — do not edit
const __exportLazy = (name, path) => {
    let mod;
    Object.defineProperty(exports, name, {
        enumerable: true,
        configurable: true,
        get() { return (mod ??= require(path))[name]; },
    });
};
__exportLazy('CatalogModelInfo', './CatalogModelInfo.js');
__exportLazy('CatalogModelInstance', './CatalogModelInstance.js');
__exportLazy('CatalogModelInstanceResult', './CatalogModelInstanceResult.js');
__exportLazy('CatalogModelInstanceStatus', './CatalogModelInstanceStatus.js');
__exportLazy('CatalogModelStatus', './CatalogModelStatus.js');
__exportLazy('ExecutionProvider', './ExecutionProvider.js');
__exportLazy('ExecutionProviderCatalog', './ExecutionProviderCatalog.js');
__exportLazy('ExecutionProviderCertification', './ExecutionProviderCertification.js');
__exportLazy('ExecutionProviderReadyResult', './ExecutionProviderReadyResult.js');
__exportLazy('ExecutionProviderReadyResultState', './ExecutionProviderReadyResultState.js');
__exportLazy('ExecutionProviderReadyState', './ExecutionProviderReadyState.js');
__exportLazy('ModelCatalog', './ModelCatalog.js');
__exportLazy('ModelCatalogSource', './ModelCatalogSource.js');
__exportLazy('createProjectedLifetimeScope', './lifetime.js');
__exportLazy('projectAs', './lifetime.js');
__exportLazy('releaseProjected', './lifetime.js');
0 && (module.exports = {
    CatalogModelInfo,
    CatalogModelInstance,
    CatalogModelInstanceResult,
    CatalogModelInstanceStatus,
    CatalogModelStatus,
    ExecutionProvider,
    ExecutionProviderCatalog,
    ExecutionProviderCertification,
    ExecutionProviderReadyResult,
    ExecutionProviderReadyResultState,
    ExecutionProviderReadyState,
    ModelCatalog,
    ModelCatalogSource,
    createProjectedLifetimeScope,
    projectAs,
    releaseProjected,
});
