// Generated by dynwinrt-codegen — do not edit
const __lazy = (load) => {
    const target = class {};
    const targetKeys = new Set(Reflect.ownKeys(target));
    return new Proxy(target, {
        get(t, prop) { return prop in Object(load()) ? Reflect.get(load(), prop) : Reflect.get(t, prop); },
        set(_, prop, value) { return Reflect.set(load(), prop, value); },
        construct(_, args) { return Reflect.construct(load(), args); },
        apply(_, thisArg, args) { return Reflect.apply(load(), thisArg, args); },
        has(t, prop) { return prop in Object(load()) || Reflect.has(t, prop); },
        ownKeys(t) {
            const loaded = load();
            const loadedKeys = loaded != null ? Reflect.ownKeys(Object(loaded)) : [];
            return Array.from(new Set([...loadedKeys, ...Reflect.ownKeys(t)]));
        },
        getOwnPropertyDescriptor(t, prop) {
            if (targetKeys.has(prop)) return Reflect.getOwnPropertyDescriptor(t, prop);
            const loaded = load();
            const d = loaded != null ? Reflect.getOwnPropertyDescriptor(Object(loaded), prop) : undefined;
            if (d) d.configurable = true;
            return d;
        },
        getPrototypeOf() { return Reflect.getPrototypeOf(Object(load())); },
    });
};
{ let _m; exports.CatalogModelInfo = __lazy(() => (_m ??= require('./CatalogModelInfo.js')).CatalogModelInfo); }
{ let _m; exports.CatalogModelInstance = __lazy(() => (_m ??= require('./CatalogModelInstance.js')).CatalogModelInstance); }
{ let _m; exports.CatalogModelInstanceResult = __lazy(() => (_m ??= require('./CatalogModelInstanceResult.js')).CatalogModelInstanceResult); }
{ let _m; exports.CatalogModelInstanceStatus = __lazy(() => (_m ??= require('./CatalogModelInstanceStatus.js')).CatalogModelInstanceStatus); }
{ let _m; exports.CatalogModelStatus = __lazy(() => (_m ??= require('./CatalogModelStatus.js')).CatalogModelStatus); }
{ let _m; exports.ExecutionProvider = __lazy(() => (_m ??= require('./ExecutionProvider.js')).ExecutionProvider); }
{ let _m; exports.ExecutionProviderCatalog = __lazy(() => (_m ??= require('./ExecutionProviderCatalog.js')).ExecutionProviderCatalog); }
{ let _m; exports.ExecutionProviderCertification = __lazy(() => (_m ??= require('./ExecutionProviderCertification.js')).ExecutionProviderCertification); }
{ let _m; exports.ExecutionProviderReadyResult = __lazy(() => (_m ??= require('./ExecutionProviderReadyResult.js')).ExecutionProviderReadyResult); }
{ let _m; exports.ExecutionProviderReadyResultState = __lazy(() => (_m ??= require('./ExecutionProviderReadyResultState.js')).ExecutionProviderReadyResultState); }
{ let _m; exports.ExecutionProviderReadyState = __lazy(() => (_m ??= require('./ExecutionProviderReadyState.js')).ExecutionProviderReadyState); }
{ let _m; exports.ModelCatalog = __lazy(() => (_m ??= require('./ModelCatalog.js')).ModelCatalog); }
{ let _m; exports.ModelCatalogSource = __lazy(() => (_m ??= require('./ModelCatalogSource.js')).ModelCatalogSource); }
{ let _m; exports.createProjectedLifetimeScope = __lazy(() => (_m ??= require('./lifetime.js')).createProjectedLifetimeScope); }
{ let _m; exports.projectAs = __lazy(() => (_m ??= require('./lifetime.js')).projectAs); }
{ let _m; exports.releaseProjected = __lazy(() => (_m ??= require('./lifetime.js')).releaseProjected); }
