// Generated by dynwinrt-codegen — do not edit
import { DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_IKeyValuePair_String_String } from './IIterable_IKeyValuePair_String_String.js';

export declare const IID_ModelCatalogSource: WinGuid;
/**
 * Represents a source that provides model catalog data.
 */
export declare class ModelCatalogSource {
    private constructor();
    /**
     * Creates a model catalog source from the specified URI.
     * @param location The URI of the catalog source.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that returns the created catalog source.
     */
    static createFromUriAsync(location: DynWinRtValue, signal?: AbortSignal): Promise<ModelCatalogSource>;
    static createFromUriAsync(location: DynWinRtValue, additionalHeaders: IIterable_IKeyValuePair_String_String, signal?: AbortSignal): Promise<ModelCatalogSource>;
    /**
     * Gets the catalog source identifier.
     */
    get id(): string;
    /**
     * Gets the URI where the catalog source can be accessed.
     */
    get uri(): DynWinRtValue;
}
