// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_CatalogModelInfo;
const __load_CatalogModelInfo = () => (__m_CatalogModelInfo ??= require('./CatalogModelInfo.js'));
const __get_CatalogModelInfo = () => __load_CatalogModelInfo().CatalogModelInfo;
let __m_ModelCatalogSource;
const __load_ModelCatalogSource = () => (__m_ModelCatalogSource ??= require('./ModelCatalogSource.js'));
const __get_ModelCatalogSource = () => __load_ModelCatalogSource().ModelCatalogSource;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IModelCatalog = WinGuid.parse('8cae018c-49f5-5080-abb8-ef4a1df356da');
const IID_IModelCatalogFactory = WinGuid.parse('2942d7bd-6243-511f-a12c-42cb151b625f');
const IID_ModelCatalog = WinGuid.parse('8cae018c-49f5-5080-abb8-ef4a1df356da');
const IID_ARG_Microsoft_Windows_AI_MachineLearning_ModelCatalogSource = WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9');

let _IModelCatalogCache;
const _IModelCatalog = new Proxy({}, {
    get(_target, prop) {
        _IModelCatalogCache ??= DynWinRtType.registerInterface(
        "IModelCatalog", IID_IModelCatalog)
        .addMethod("get_Sources", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("get_ExecutionProviders", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("GetAvailableModel", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', DynWinRtType.interface(WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4')))))
        .addMethod("GetAvailableModels", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
        .addMethod("FindModelAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', DynWinRtType.interface(WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))))))
        .addMethod("FindAllModelsAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.object())));
        const value = _IModelCatalogCache[prop];
        return typeof value === 'function' ? value.bind(_IModelCatalogCache) : value;
    }
});

let _IModelCatalogFactoryCache;
const _IModelCatalogFactory = new Proxy({}, {
    get(_target, prop) {
        _IModelCatalogFactoryCache ??= DynWinRtType.registerInterface(
        "IModelCatalogFactory", IID_IModelCatalogFactory)
        .addMethod("CreateInstance", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', DynWinRtType.interface(WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalog', DynWinRtType.interface(WinGuid.parse('8cae018c-49f5-5080-abb8-ef4a1df356da')))));
        const value = _IModelCatalogFactoryCache[prop];
        return typeof value === 'function' ? value.bind(_IModelCatalogFactoryCache) : value;
    }
});

/**
 * Represents a collection of model catalog sources that can be searched for available models.
 */
class ModelCatalog {
    _obj;
    static _f_IModelCatalogFactory;
    static f_IModelCatalogFactory() { return ModelCatalog._f_IModelCatalogFactory ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.MachineLearning.ModelCatalog').cast(IID_IModelCatalogFactory); }

    constructor(...args) {
        if (args.length === 1) {
            this._obj = ModelCatalog.createInstance(args[0])._obj;
            return;
        }
        throw new TypeError('No matching constructor for ModelCatalog.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(ModelCatalog.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_IModelCatalog, 'ModelCatalog') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(ModelCatalog.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_IModelCatalog, 'ModelCatalog') });
    }
    static createInstance(sources) {
        return ModelCatalog._fromNative(_IModelCatalogFactory.method(6).invoke(ModelCatalog.f_IModelCatalogFactory(), [(Array.isArray(sources) ? DynWinRtArray.fromObjectValues(sources.map(_i => _unwrap(_i).cast(IID_ARG_Microsoft_Windows_AI_MachineLearning_ModelCatalogSource)), DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', DynWinRtType.interface(WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9')))).toValue() : _unwrap(sources))]));
    }
    /**
     * Gets the catalog sources used during model lookup and discovery operations.
     */
    get sources() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _IModelCatalog.method(6); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets the execution provider names used when finding and filtering models in the catalog.
     */
    get executionProviders() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _IModelCatalog.method(7); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
    /**
     * Gets a locally available model by name or full identifier.
     * @param idOrName The model identifier or name.
     * @returns The matching locally available model, or null if no matching model is available.
     */
    getAvailableModel(idOrName) {
        return ((v) => v.isNull() ? null : (__get_CatalogModelInfo())._fromNative(v))(_IModelCatalog.method(8).invoke(this._obj, [DynWinRtValue.hstring(idOrName)]));
    }
    /**
     * Retrieves all locally available models from the catalog.
     * @returns The locally available models.
     */
    getAvailableModels() {
        return ((v) => v.isNull() ? null : v)(_IModelCatalog.method(9).invoke(this._obj, []));
    }
    /**
     * Finds a model across all catalog sources that matches the specified name or full identifier.
     * @param idOrName The model identifier or name.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that returns the matching model, or null if no matching model is found.
     */
    async findModelAsync(idOrName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IModelCatalog.method(10).invoke(this._obj, [DynWinRtValue.hstring(idOrName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_CatalogModelInfo())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Finds all models across all catalog sources.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that returns all matching models.
     */
    async findAllModelsAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IModelCatalog.method(11).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : v)(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
exports.IID_ModelCatalog = IID_ModelCatalog;
exports.ModelCatalog = ModelCatalog;
