// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_CatalogModelInfo } from './IVectorView_CatalogModelInfo.js';
import { IVector_CatalogModelInfo } from './IVector_CatalogModelInfo.js';
import { IVector_ModelCatalogSource } from './IVector_ModelCatalogSource.js';
import { IVector_String } from './IVector_String.js';
import { CatalogModelInfo } from './CatalogModelInfo.js';
import { ModelCatalogSource } from './ModelCatalogSource.js';

export declare const IID_ModelCatalog: WinGuid;
/**
 * Represents a collection of model catalog sources that can be searched for available models.
 */
export declare class ModelCatalog {
    constructor(sources: ModelCatalogSource[]);
    static createInstance(sources: ModelCatalogSource[]): ModelCatalog;
    /**
     * Gets the catalog sources used during model lookup and discovery operations.
     */
    get sources(): IVector_ModelCatalogSource;
    /**
     * Gets the execution provider names used when finding and filtering models in the catalog.
     */
    get executionProviders(): IVector_String;
    /**
     * Gets a locally available model by name or full identifier.
     * @param idOrName The model identifier or name.
     * @returns The matching locally available model, or null if no matching model is available.
     */
    getAvailableModel(idOrName: string): CatalogModelInfo;
    /**
     * Retrieves all locally available models from the catalog.
     * @returns The locally available models.
     */
    getAvailableModels(): IVector_CatalogModelInfo;
    /**
     * Finds a model across all catalog sources that matches the specified name or full identifier.
     * @param idOrName The model identifier or name.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that returns the matching model, or null if no matching model is found.
     */
    findModelAsync(idOrName: string, signal?: AbortSignal): Promise<CatalogModelInfo>;
    /**
     * Finds all models across all catalog sources.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that returns all matching models.
     */
    findAllModelsAsync(signal?: AbortSignal): Promise<IVectorView_CatalogModelInfo>;
}
