// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IModelCatalogSource = WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9');
const IID_IModelCatalogSourceStatics = WinGuid.parse('deba0a9b-6eda-571a-9a05-5a7e2a0531ef');
const IID_ModelCatalogSource = WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9');

let _IModelCatalogSourceCache;
const _IModelCatalogSource = new Proxy({}, {
    get(_target, prop) {
        _IModelCatalogSourceCache ??= DynWinRtType.registerInterface(
        "IModelCatalogSource", IID_IModelCatalogSource)
        .addMethod("get_Id", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Uri", new DynWinRtMethodSig().addOut(DynWinRtType.object()));
        const value = _IModelCatalogSourceCache[prop];
        return typeof value === 'function' ? value.bind(_IModelCatalogSourceCache) : value;
    }
});

let _IModelCatalogSourceStaticsCache;
const _IModelCatalogSourceStatics = new Proxy({}, {
    get(_target, prop) {
        _IModelCatalogSourceStaticsCache ??= DynWinRtType.registerInterface(
        "IModelCatalogSourceStatics", IID_IModelCatalogSourceStatics)
        .addMethod("CreateFromUriAsync", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', DynWinRtType.interface(WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))))
        .addMethod("CreateFromUriAsync2", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addIn(DynWinRtType.object()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', DynWinRtType.interface(WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))));
        const value = _IModelCatalogSourceStaticsCache[prop];
        return typeof value === 'function' ? value.bind(_IModelCatalogSourceStaticsCache) : value;
    }
});

/**
 * Represents a source that provides model catalog data.
 */
class ModelCatalogSource {
    _obj;
    static _s_IModelCatalogSourceStatics;
    static s_IModelCatalogSourceStatics() { return ModelCatalogSource._s_IModelCatalogSourceStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource').cast(IID_IModelCatalogSourceStatics); }

    constructor() {
        throw new TypeError('ModelCatalogSource cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(ModelCatalogSource.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_IModelCatalogSource, 'ModelCatalogSource') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(ModelCatalogSource.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_IModelCatalogSource, 'ModelCatalogSource') });
    }
    static async _createFromUriAsync_1(location, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IModelCatalogSourceStatics.method(6).invoke(ModelCatalogSource.s_IModelCatalogSourceStatics(), [(location == null ? DynWinRtValue.nullValue() : _unwrap(location))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : ModelCatalogSource._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async _createFromUriAsync_2(location, additionalHeaders, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IModelCatalogSourceStatics.method(7).invoke(ModelCatalogSource.s_IModelCatalogSourceStatics(), [(location == null ? DynWinRtValue.nullValue() : _unwrap(location)), _unwrap(additionalHeaders)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : ModelCatalogSource._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Creates a model catalog source from the specified URI.
     * @param location The URI of the catalog source.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     * @returns An asynchronous operation that returns the created catalog source.
     */
    static createFromUriAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._createFromUriAsync_2(args[0], args[1], args[2]);
        }
        return this._createFromUriAsync_1(args[0], args[1]);
    }
    /**
     * Gets the catalog source identifier.
     */
    get id() {
        return (() => { const _m = _IModelCatalogSource.method(6); return typeof _m.getString === 'function' ? _m.getString(this._obj) : _IModelCatalogSource.method(6).invoke(this._obj, []).toString(); })();
    }
    /**
     * Gets the URI where the catalog source can be accessed.
     */
    get uri() {
        return ((v) => v.isNull() ? null : v)((() => { const _m = _IModelCatalogSource.method(7); return typeof _m.getObj === 'function' ? _m.getObj(this._obj) : _m.invoke(this._obj, []); })());
    }
}
exports.IID_ModelCatalogSource = IID_ModelCatalogSource;
exports.ModelCatalogSource = ModelCatalogSource;
